### ISSUE TITLE
Context menu on right click

### ISSUE THREAD

**Issue by erming** [erming/shout#31]
Inspired by Dropbox:
![context](https://cloud.githubusercontent.com/assets/2502500/3952429/3a682d0a-26e2-11e4-9d79-0ec14b37f1d6.png)

Here's some example context menus:

**Right click on user**
- Kick
- Kick & Ban
- Op / Deop
- Voice / Devoice

**Right click on channel**
- Get topic
- Leave

**Right click on network**
- Set nick
- Quit

**Comment by FlamingOysterDK** [comment]
This is a much needed feature! :)

**Comment by astorije** [comment]
Marking this issue as `help wanted`. It seems like a very desired feature, does anyone want to give a shot at implementing it? :-)
If so, then please share your implementation design here so that we are all on the same page before anyone wastes their time!

**Comment by YaManicKill** [comment]
Just reading through some past issues and throwing my thoughts into them (as well as trying not to partly implement everything).

We could remove the default of clicking on a user to query them, and instead clicking on the user could bring up the context menu. Really easy to ifnd out what to do (and because it'll have a query user option, not **too** annoying for users who like to click to query).

**Comment by xPaw** [comment]
Initial work done in #613
