### ISSUE TITLE
Don't fetch `localhost` links

### ISSUE THREAD

**Issue by jsocol** [erming/shout#388]
When someone posts a `localhost` link, there's still a fetch, which is both obviously not valuable (since it seems to fetch Shout) and potentially risky (I don't know of any immediate exploit but I haven't looked either).

Planning to submit a patch, just wanted to write it down for myself (or someone who beats me to it).

**Comment by erming** [comment]
I don't think there's any potentinal risks here. It can only fetch public files (not internal) hosted from http://localhost/. The server would have to serve the file you link to, otherwise it will just 404. Also, it's capped to 10mb max-size for a document it tries to fetch.

You've probably already seen the code, but I link it anyway:
https://github.com/erming/shout/blob/master/src/plugins/irc-events/link.js

I agree with you though, it's not valuable and it should be blocked.

**Comment by erming** [comment]
Fixed here: https://github.com/erming/shout/commit/29b66ff0ec6bdd67c7c3168c383efe00bf94f75f

The link is still clickable but it will not be fetched and have its headers read etc.

Thanks man!

**Comment by jsocol** [comment]
Thanks! I got busy and didn't have a chance to follow-through.
