### ISSUE TITLE
Move topic near #channel name?

### ISSUE THREAD

**Issue by nwgat** [erming/shout#393]
move topic on the side of #channel name? that way its always there so you dont need to scroll a million lines to get it to or have to part and join the channel

![image](https://cloud.githubusercontent.com/assets/5809156/7000457/9908e8c6-dc23-11e4-9071-c532bffbe76d.png)

**Comment by erming** [comment]
You can write `/topic` to see it.

But anyway.. Some time ago I was playing around with the design and I put the topic up there to try it out. But I couldn't make it look as good as I wanted, handling really long topics etc, so I gave up.

Not sure if I will implement it. But maybe I could make it easier by adding some kind of dropdown on the top right for common actions like "Show/Set topic", "Leave channel" and so on. 

I'll close this issue because I don't think I'll implement it. But if I change my mind I will open it again.

Thanks!

**Comment by nwgat** [comment]
a really simple one would be run /topic on re-connect and login
