### ISSUE TITLE
Allow users to register

### ISSUE THREAD

**Issue by lizardsrock4** [erming/shout#413]
It would be great if in your config you could enable users to register, that when enabled, adds a register button on the login page that lets users make an account, so they don't need to be added by an admin, and don't need the admin knowing their password

**Comment by erming** [comment]
Hey man,

I decided a while ago that I would not implement this. If someone wants to build their own administration of users they will have to build it themselves.

There's a couple of reasons I don't feel like implement it:
- It's alot of extra work
- What happens when someone loses their password? Now people would ask me to implement password recovery by email, email activation, name changes, unregister etc
- Because of how Shout works (it's like a proxy) users will share the same IP when connecting to networks; having public registration might break the connection limit on some networks.
- It might open up for exploits and other security issues. (On the top of my head: mass creation of users would be pretty bad)

But yes, it would be sweet if it was ever implemented! I might change my mind in the future, but for now, manual administration will have to do, I'm sorry.

**Comment by lizardsrock4** [comment]
Thanks for the quick reply!
