### ISSUE TITLE
Parse GFM/LaTeX/etc

### ISSUE THREAD

**Issue by dbkaplun** [erming/shout#435]

**Comment by astorije** [comment]
That would be nice indeed. Anyone wants to take a shot at this? Please share implementation design here first.

**Comment by floogulinc** [comment]
Things like this are where I think we should have a plugin system. I think the core client should stick to being an IRC client and if users want a feature like this they should be able to add a plugin (client or server side). Another example would bit github style emoji.

**Comment by astorije** [comment]
I'm not sure about having yet another a plugin system. I love the plugin system  of some of some software, but that's because I'm a geek: plugin systems are usually a beast for non-tech savvy people.
Let's keep the plugin system discussion aside. If we are going for one, it has to be dead simple for the user, i.e. provide sensible defaults for all.

**Comment by astorije** [comment]
I am closing this issue as we will not implement it in the current state of Shout. However, we (and I invite the community when I say "we") are/will come up with a plugin system that should be used as a base for this.

I invite you to stop by the roadmap (https://github.com/erming/shout-roadmap) and discuss in issues and PRs what you have on your mind regarding Shout, an hypothetical plugin system, and plugin ideas such as this one.
