### ISSUE TITLE
Use localStorage instead of cookies for storage

### ISSUE THREAD

**Issue by xPaw** [erming/shout#604]
Using cookies is silly to persist settings. Ideally logged in users would persist their settings on the server.

**Comment by MaxLeiter** [comment]
Alternaitvley, we can update to [js-cookie](https://github.com/js-cookie/js-cookie/tree/v1.5.1), jquery.cookie.js's successor (what we currently use).

**Comment by xPaw** [comment]
That doesn't change the fact that settings are stored in cookies, which is not a good idea.

**Comment by astorije** [comment]
I agree, we'd better off using localStorage, and that is also highlighted by Shout becoming a more and more powerful web app.

I do believe however that this is just one step among the grand scheme of clean user settings management. I started to gather broad thoughts on design/requirements of user settings and will publish them soon, probably in a wiki page or an issue, so that we can discuss about it and reach the best solution :-)
It would be interesting to also gather up all opened tickets (and maybe closed too?) that are related to that as they add or specify requirements.

**Comment by MaxLeiter** [comment]
It could be beneficial to save settings server-side if shout is in private, and then use localStorage if public. That way, a users settings can persist across devices. Users already have a config file for saving channels and networks

**Comment by xPaw** [comment]
Fixed in lounge.
