### ISSUE TITLE
Allow edit base_path

### ISSUE THREAD

**Issue by zaggash** [erming/shout#607]
Hi,

It would be nice to add an option to edit the base_path. ( which is / at the moment )
This would be easier/more flexible with reverse proxy.

Like mybesite.com/shout

**Comment by carlwgeorge** [comment]
:+1: I would like this feature so I can proxy shout behind my existing nginx setup.

**Comment by snpster** [comment]
you can do this with passenger to handle the app behind nginx or apache.

**Comment by astorije** [comment]
Hey guys, just enquiring, is it what https://github.com/thelounge/lounge/pull/27 attempts to offer?

**Comment by carlwgeorge** [comment]
@astorije Yup, looks like it.

**Comment by zaggash** [comment]
May I ask here what is the differance between both versions ( shout and thelounge ? )

**Comment by astorije** [comment]
Hi @carlwgeorge and @zaggash,

thelounge/lounge#27 was merged and shipped in v1.1.0 (currently at v1.2.0) so you should be all set there.

Also, I am listing the technical differences between the 2 projects here: https://github.com/thelounge/lounge/wiki/Differences-between-The-Lounge-and-Shout
I will try to keep this list fairly up-to-date as the projects evolve (only The Lounge has had activity since the fork so far). Let me know if that helps or not, and how we could improve this.

**Comment by zaggash** [comment]
Closing as deprecated repo
