### ISSUE TITLE
Document required nodejs version

### ISSUE THREAD

**Issue by hho** [erming/shout#651]
Currently `npm install -g shout` only works with nodejs >=0.10.40 <0.11.0 (because of outdated dependencies, which three levels deep finally require ws@0.4.31).

It would be nice to document this, as most people probably have nodejs 4.x or 5.x installed.

(node 0.10.29 from Debian Jessie doesn't work, because some dependencies expect at least 0.10.40; node 4.x and 5.x don't work because ws 0.4.31 won't compile anymore).

**Comment by astorije** [comment]
Interestingly enough, we just had a discussion about this on https://github.com/thelounge/lounge/pull/43 and decided to drop CI builds on Node 0.10 (https://github.com/thelounge/lounge/pull/60). We were saying that we could still keep Node 0.10 support due to the fact that Debian comes with it, but yes, I forgot that less and less packages will support it anyway.

@JocelynDelalande, should we document this somewhere?

**Comment by JocelynDelalande** [comment]
@hho interesting digging and remark about Debian versions, I'll check that out.

> We were saying that we could still keep Node 0.10 support due to the fact that Debian comes with it, but yes, I forgot that less and less packages will support it anyway.

Could you reword the question ?

**Comment by astorije** [comment]
What question? That quote means: Even though Shout / The Lounge source code by itself is compatible with Node.js v0.10.x, some of its dependencies are no longer compatible with this version.

I was asking if we should document that Shout / The Lounge are not compatible with the version of Node.js that comes with Debian Jessie by default.
