### ISSUE TITLE
Moving dependencies to external file so that it is not packed with the code

### ISSUE THREAD

**Issue by Rafi993** [erming/shout#693]
Shout source repo is also packed with external dependency like Jquery, Moment etc.. wouldn't it be good if these dependencies are just installed via npm and then built using grunt so that they don't need to be pushed with the source repo.

**Comment by astorije** [comment]
Hi @Rafi993!

You probably noticed that development of Shout has stalled. If you take a look at [this section of the README](https://github.com/erming/shout#official-forks), you'll notice that active development has moved to [The Lounge](https://github.com/thelounge/lounge).

And your suggestion makes so much sense that it was in fact done there: https://github.com/thelounge/lounge/pull/817
Difference is that we use Webpack + npm scripts instead of Grunt now, but yeah, everything is built off npm now :)

👋
