### ISSUE TITLE
Chrome Plugin

### ISSUE THREAD

**Issue by jimmyxander** [erming/shout#92]
In browser is great, but in some cases a chromeplugin might be better, for people like me who have a chromebook, it would be nice to be able to get notifications from SHOUT.

**Comment by ashelley** [comment]
Hello,

This is a very crude initial commit.  I am posting this here in case anyone else becomes interested in it.

I used browserify to convert shout.js into a chrome-app.

This is the steps i did:

1) created an app directory

https://github.com/ashelley/shout/tree/master/client/app

- https://github.com/ashelley/shout/blob/master/client/app/background.js

a file required by chrome-app to run

- https://github.com/ashelley/shout/blob/master/client/app/app.js

the browserified version of shout.js with shims (see below)

- https://github.com/ashelley/shout/blob/master/client/app/app.html

a standalone (non-templated version of index.html that background.js points to to load)

2) add a manifest.json file required for chrome-app

https://github.com/ashelley/shout/blob/master/client/manifest.json

- this file setups up permissions to use chrome.sockets

3) to create the browserify app.js file you need to do the following:

https://github.com/ashelley/shout/blob/master/package.json#L18-20

Basically you need to npm install chrome-net and use that as a shim for require('net');

https://github.com/feross/chrome-net

4) browserify doesn't work on dynamic requires so I hacked client.js temporarily to statically reference irc-event and input plugins:

https://github.com/ashelley/shout/blob/master/src/client.js#L53-87
https://github.com/ashelley/shout/blob/master/src/client.js#L227-237
https://github.com/ashelley/shout/blob/master/src/client.js#L280-292

5) Because src/client.js is tightly coupled with web sockets I created a shim event emitter.  I ended up copying a bunch of code from server.js + the event emitter pretend socket.io into my pre-browserified app.js file:

https://github.com/ashelley/shout/blob/master/app_ts/app.js

6) browerify app.js into the client

browerify app_ts/app.js /client/js/app/app.js

7) use chrome more tools/extensions and "load unpacked extension and chose ./client in the repo

8) click launch.

Client works!

I'm sure there are some issues but I just wanted to show the proof of concept.

![image](https://cloud.githubusercontent.com/assets/3195045/5832116/e284e46a-a0f4-11e4-875c-30572a719e29.png)

Note that the undefined is not a function error is client.save trying to save the config file to local file system.   Also note that right now I hacked it so it can only support one socket at a time so only one network.

**Comment by YaManicKill** [comment]
I'm not sure what this would add, 18 months later. I don't believe there is anything that a chrome extension would give us that the web doesn't (especially as the only thing quoted originally was notifications). We can even get push notifications when the tab isn't opened if we want to go that way.

**Comment by astorije** [comment]
Agreed with @YaManicKill.
